time_gap: 10
core_file_dir: "/Users/feiyilin/downloads"

subject: "CORE文件通知"
sender_email: "miyuk1@126.com"
receiver_email: "feiyl48657@hundsun.com"
smtp_server: "smtp.126.com"
smtp_port: 465
sender_password: "PEJBYLYTFLXQGZDQ"
